name: Print some text every 3rd minute
on:
  schedule:
    - cron: '1/3 * * * *'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      text_to_print:
        description: 'What text do you want to print?'
        required: true
        default: 'Periodically printing passages'
      number_to_print:
        description: 'What number do you want to print?'
        required: true
        default: 10

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        env:
          DEFAULT_MESSAGE: 'Periodically printing passages' # here is the default message
          DEFAULT_NUMBER: 10
        run: |
          echo "MESSAGE=${{ github.event.inputs.text_to_print || env.DEFAULT_MESSAGE }}" >> $GITHUB_ENV
          echo "NUMBER=${{ github.event.inputs.number_to_print || env.DEFAULT_NUMBER }}" >> $GITHUB_ENV

      - name: Print some text
        run: echo "$MESSAGE - $NUMBER"
